
export class MessageUtil {
    static REGISTRY_SUCCESS_CREATED: string = 'REGISTRY_SUCCESS_CREATED';
    static REGISTRY_SUCCESS_UPDATED: string = 'REGISTRY_SUCCESS_UPDATED';
    static REGISTRY_SUCCESS_DELETE: string = 'REGISTRY_SUCCESS_DELETE';
    //static REGISTRY_SUCCESS_CREATED: string = 'REGISTRY_SUCCESS_CREATED';
    static INVALID_LOGIN_OR_PASSWORD: string = 'INVALID_LOGIN_OR_PASSWORD';
    static INTERNAL_SERVER_ERROR: string = 'INTERNAL_SERVER_ERROR';
    static CREATE_ERROR_DATA: string = 'CREATE_ERROR_DATA';
    static UPDATE_ERROR_DATA: string = 'UPDATE_ERROR_DATA';
    static LIST_ERROR_DATA: string = 'LIST_ERROR_DATA';
    static FIND_ERROR_DATA: string = 'FIND_ERROR_DATA';
    static NOT_FOUND_REGISTER: string = 'NOT_FOUND_REGISTER';
    static DELETE_ERROR_DATA: string = 'FIND_ERROR_DATA';
    static PASSWORD_NOT_MATCH_ERROR: string = 'PASSWORD_NOT_MATCH_ERROR';
}
