

export class SettingUtil {
    static WEBPORTAL_ACCOUNT_ID: string = 'WEBPORTAL_ACCOUNT_ID';
    static WEBPORTAL_ACCOUNT_PASSWORD: string = 'WEBPORTAL_ACCOUNT_PASSWORD';
    static WEBPORTAL_ACCOUNT_URL: string = 'WEBPORTAL_ACCOUNT_URL';
    static WEBPORTAL_ACCOUNT_PREFIX: string = 'WEBPORTAL_ACCOUNT_PREFIX';
}
